### ISSUE TITLE
Possible to extend syntax highlighting? 

### ISSUE THREAD

**Issue by jtleek** [jjallaire/revealjs#10]
Is there an easy way to extend syntax highlighting to include github or other white background highlighting styles?

**Comment by jtleek** [comment]
Sorry if this is just a css thing that I'm not seeing

**Comment by jjallaire** [comment]
Yes, you can use the "highlight" option to change the syntax highlighting
(see https://github.com/jjallaire/revealjs#appearance-and-style)

**Comment by jtleek** [comment]
Sorry I meant, I used various settings for the highlight option, but all seemed to have a dark background. I would like to use for example, the "github" highlighting scheme. Is it easy to extend the list of themes (currently "kate", "espresso", etc.) to include all of highlight.js?

**Comment by jjallaire** [comment]
No, that's not super straightforward (possible but not a quick fix). You
could always fork the repo and try to make the change to the underlying
template though.

**Comment by jtleek** [comment]
Thanks for the quick response! I have a short term deadline so probably can't dig in right now, but will circle back around.
