### ISSUE TITLE
Error when self_contained:false

### ISSUE THREAD

**Issue by yutannihilation** [jjallaire/revealjs#18]
Thanks for this great package!

revealjs won't work correctly when I specify `self_contained: false`. I got this error in Javascript Console:

```
ReferenceError: Reveal is not defined
```

Rmd: https://raw.githubusercontent.com/yutannihilation/presentation_with_htmlwidgets_test/gh-pages/grViz_revealjs_noselfcontained.Rmd
knitted html: https://yutannihilation.github.io/presentation_with_htmlwidgets_test/grViz_revealjs_noselfcontained.Rmd

It works fine when `self_contained:false` is not added.

Rmd: https://raw.githubusercontent.com/yutannihilation/presentation_with_htmlwidgets_test/gh-pages/grViz_revealjs.Rmd
knitted html: https://yutannihilation.github.io/presentation_with_htmlwidgets_test/grViz_revealjs.html

Sorry, I could not specify the cause of this problem... Hope this information is useful for improving your package.

**Comment by jjallaire** [comment]
I'm unable to reproduce this problem (even with your simple test code). I tested on Mac OS X 10.9 both inside RStudio and in Google Chrome.

Maybe there is an older version of reveal in the _files directory. Have you tried removing that directory then re-kniting? If that doesn't work out then any additional details which would allow us to reproduce would be much appreciated.

**Comment by yutannihilation** [comment]
Thanks for quick testing and kind advice!

You are right. This was some problem related to my Windows environment.... I found one of the path separators is `\`(backslash), not `/`(slash) here:

```html
  <script src="grViz_revealjs_noselfcontained_files\revealjs_presentation/lib/js/head.min.js"></script>
  <script src="grViz_revealjs_noselfcontained_files\revealjs_presentation/js/reveal.min.js"></script>
```
(https://github.com/yutannihilation/presentation_with_htmlwidgets_test/blob/3e859ed00e2b15244a22ba5677c6e6c7f1363d16/grViz_revealjs_noselfcontained.html#L98-L99)

Maybe something is wrong with my environment, not with your package. I'm sorry for reporting incorrect issue here.
