### ISSUE TITLE
Using custom css

### ISSUE THREAD

**Issue by PMassicotte** [jjallaire/revealjs#20]
Hi all.

Is it possible to use external CSS with revealjs_presentation? For some reasons, it is not reading my CSS file.

     ---
     title: "title"
     output:
       revealjs::revealjs_presentation:
         css: styles.css
     ---

However, if I specify it directly in the .Rmd file it works.

Any ideas?

Philippe

**Comment by jjallaire** [comment]
Fixed via https://github.com/jjallaire/revealjs/commit/fad5523bc0427824afdf9a630b57ea2fa33d5469
