### ISSUE TITLE
Adding notes (and then seeing them)

### ISSUE THREAD

**Issue by sje30** [jjallaire/revealjs#22]
Hi @jjallaire 
Thanks for a great package.  Already used this on a shot talk I gave yesterday. https://github.com/sje30/2015-11-17-ebi

How do I add notes to my presentation, and how do I view them (I couldn't get "s" keystroke to work.)

best wishes, Stephen

**Comment by jjallaire** [comment]
Unfortunately I don't think the way reveal does speaker notes (running a
node js server) is compatible with the revealjs bindings for R.

**Comment by sje30** [comment]
ok, thanks JJ.
